### ISSUE TITLE
placed a copper tank down and crash 1.11.2 forge

### ISSUE THREAD

**Issue by Gamezxtrem** [Indemnity83/irontank#44]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (Backpacks 1.11.2 - 3.1.9.jar)
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  IC2core (industrialcraft-2-2.7.74-ex111.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 10/9/17 6:55 PM
Description: Ticking block entity

java.lang.NoSuchFieldError: tank
	at com.indemnity83.irontanks.common.tiles.TileTank.<init>(TileTank.java:17)
	at com.indemnity83.irontanks.common.tiles.TileCopperTank.<init>(TileCopperTank.java:5)
	at com.indemnity83.irontanks.common.blocks.IronTankType.makeEntity(IronTankType.java:92)
	at com.indemnity83.irontanks.common.blocks.BlockIronTank.func_149915_a(BlockIronTank.java:183)
	at net.minecraft.block.Block.createTileEntity(Block.java:1224)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784)
	at net.minecraft.world.World.func_175625_s(World.java:2357)
	at buildcraft.transport.tile.TilePipeHolder.getNeighbouringTile(TilePipeHolder.java:366)
	at buildcraft.transport.pipe.Pipe.onTick(Pipe.java:218)
	at buildcraft.transport.tile.TilePipeHolder.func_73660_a(TilePipeHolder.java:182)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.indemnity83.irontanks.common.tiles.TileTank.<init>(TileTank.java:17)
	at com.indemnity83.irontanks.common.tiles.TileCopperTank.<init>(TileCopperTank.java:5)
	at com.indemnity83.irontanks.common.blocks.IronTankType.makeEntity(IronTankType.java:92)
	at com.indemnity83.irontanks.common.blocks.BlockIronTank.func_149915_a(BlockIronTank.java:183)
	at net.minecraft.block.Block.createTileEntity(Block.java:1224)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784)
	at net.minecraft.world.World.func_175625_s(World.java:2357)
	at buildcraft.transport.tile.TilePipeHolder.getNeighbouringTile(TilePipeHolder.java:366)
	at buildcraft.transport.pipe.Pipe.onTick(Pipe.java:218)
	at buildcraft.transport.tile.TilePipeHolder.func_73660_a(TilePipeHolder.java:182)

-- Block entity being ticked --
Details:
	Name: buildcrafttransport:pipe_holder // buildcraft.transport.tile.TilePipeHolder
	Block type: ID #248 (tile.pipeHolder // buildcraft.transport.block.BlockPipeHolder)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (142,63,-217), Chunk: (at 14,3,7 in 8,-14; contains blocks 128,0,-224 to 143,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #248 (tile.pipeHolder // buildcraft.transport.block.BlockPipeHolder)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: New World 4_0
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -4582219712045372839
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (128,64,-232), Chunk: (at 0,4,8 in 8,-15; contains blocks 128,0,-240 to 143,255,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 7686 game time, 7686 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 153666 (now: false), thunder time: 168452 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2282684720 bytes (2176 MB) / 3877109760 bytes (3697 MB) up to 9544663040 bytes (9102 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 Optifine OptiFine_1.11.2_HD_U_B5 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJAAAA	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJAAAA	backpacks16840{3.1.9} [Backpacks!] (Backpacks 1.11.2 - 3.1.9.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	buildcraftlib{7.99.0} [BuildCraft Lib] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJAAAA	buildcraftcore{7.99.0} [BuildCraft] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJAAAA	buildcraftfactory{7.99.0} [BC Factory] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJAAAA	buildcrafttransport{7.99.0} [BC Transport] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJAAAA	buildcraftbuilders{7.99.0} [BC Builders] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJAAAA	buildcraftenergy{7.99.0} [BC Energy] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJAAAA	buildcraftrobotics{7.99.0} [BC Robotics] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJAAAA	buildcraftsilicon{7.99.0} [BC Silicon] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJAAAA	elevatorid{1.3.2} [Elevator Mod] (ElevatorMod-1.11.2-1.3.2.jar) 
	UCHIJAAAA	foragecraft{1.11} [ForageCraft] (ForageCraft-1.11.jar) 
	UCHIJAAAA	hopperducts{1.4.9} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.jar) 
	UCHIJAAAA	ic2{2.7.74-ex111} [IndustrialCraft 2] (industrialcraft-2-2.7.74-ex111.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-75-f4ba194} [Inventory Tweaks] (InventoryTweaks-1.62-dev-75.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCHIJAAAA	irontanks{1.0} [Iron Tanks] (irontanks-1.11.2-2.0.0.beta-1.jar) 
	UCHIJAAAA	jei{4.3.3.267} [Just Enough Items] (jei_1.11.2-4.3.3.267 .jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.7} [JourneyMap] (journeymap-1.11.2-5.4.7.jar) 
	UCHIJAAAA	lumberjack{1.0} [lumberjack] (Lumberjack-mod-by-doubledoor-1.11.2.jar) 
	UCHIJAAAA	lunatriuscore{1.1.2.39} [LunatriusCore] (LunatriusCore-1.11-1.1.2.39-universal.jar) 
	UCHIJAAAA	placeableitems{3.0.4} [Placeable Items Mod] (placeableitems-3.0.4.jar) 
	UCHIJAAAA	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.11.2-1.2.3.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	UCHIJAAAA	scannable{1.4.0.23} [Scannable] (Scannable-MC1.11.2-1.4.0.23.jar) 
	UCHIJAAAA	schematica{1.7.8.161} [Schematica] (Schematica-1.11-1.7.8.161-universal.jar) 
	UCHIJAAAA	torchmaster{1.0} [TorchMaster] (torchmaster_1.11.2-1.2.1.24.jar) 
	UCHIJAAAA	waystones{3.0.12} [Waystones] (Waystones_1.11.2-3.0.12.jar) 
	UCHIJAAAA	denseores{1.0} [denseores] (denseores-1.11-alpha-1.0.1.jar) 
	Loaded coremods (and transformers): 
BCModPlugin (Backpacks 1.11.2 - 3.1.9.jar)
  brad16840.common.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
IC2core (industrialcraft-2-2.7.74-ex111.jar)
  
FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  invtweaks.forge.asm.ContainerTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Indemnity83** [comment]
Some things to test/check:

- [ ] Update your Buildcraft version, IronTanks beta-1 is compiled against 7.99.6 and you're running 7.99.0
- [ ] Update your forge version, IronTanks beta-1 is compiled against 13.20.0.2299 and you're running 13.20.0.2282

If neither of those fixes the problem, disable all your mods except Forge, Buildcraft and IronTanks, see if that runs. If it does, add another mod back in, test that ... continue this until you find out which version causes the crash. Report that mod back here.

**Comment by Gamezxtrem** [comment]
ok so I updated my forge and the iron tanks no longer crash the game thanks Indemnity83 for your help.

**Comment by Indemnity83** [comment]
Awesome!
